trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      yarn install
      yarn compile
    displayName: "Install dependencies"

  - script: |
      yarn test
    displayName: "Run tests"
