trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      yarn install
      yarn compile
    displayName: "Install dependencies"

  - script: |
      yarn test:ci
    displayName: "Run tests"

  - task: PublishTestResults@2
    condition: succeeded()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/junit.xml"
