version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install
            yarn compile
      - run:
          name: Run Tests
          command: |
            yarn test:ci
      - store_test_results:
          path: test-results
      - codecov/upload:
          file: coverage/cobertura-coverage.xml
